from pathlib import PurePosixPath
from uuid import UUID

from app.models.architecture import (
    ArchitectureEdge,
    ArchitectureMap,
    ArchitectureNode,
    ArchitectureNodeType,
    ArchitectureRelationType,
)
from app.models.code_imports import CodeImport
from app.models.code_symbols import CodeSymbol
from app.models.project_files import ProjectFile
from app.models.project_overview import ProjectOverview
from app.models.projects import Project
from app.repositories.architecture import ArchitectureRepository
from app.repositories.code_imports import CodeImportRepository
from app.repositories.code_symbols import CodeSymbolRepository
from app.repositories.project_files import ProjectFileRepository
from app.repositories.project_overview import ProjectOverviewRepository

_CATEGORY_NAMES: dict[ArchitectureNodeType, str] = {
    "api": "API", "service": "Service", "database": "Database", "core": "Core"
}


def build_architecture_map(
    project: Project,
    files: list[ProjectFile],
    symbols: list[CodeSymbol],
    imports: list[CodeImport],
    overview: ProjectOverview | None = None,
) -> ArchitectureMap:
    """Build a graph from data generated by the preceding analysis modules."""
    root = ArchitectureNode(
        project_id=project.id, name=project.name, node_type="project",
        description=overview.purpose if overview else None,
    )
    nodes = [root]
    edges: list[ArchitectureEdge] = []
    categories: dict[ArchitectureNodeType, ArchitectureNode] = {}
    for node_type, name in _CATEGORY_NAMES.items():
        category = ArchitectureNode(
            project_id=project.id, name=name, node_type=node_type,
            parent_node_id=root.id,
        )
        categories[node_type] = category
        nodes.append(category)
        edges.append(_edge(project.id, root, category, "contains"))

    symbols_by_file: dict[UUID, list[CodeSymbol]] = {}
    for symbol in symbols:
        symbols_by_file.setdefault(symbol.file_id, []).append(symbol)

    file_nodes: dict[UUID, ArchitectureNode] = {}
    module_nodes: dict[str, ArchitectureNode] = {}
    for project_file in sorted(files, key=lambda item: item.path):
        if project_file.is_directory or project_file.category != "source":
            continue
        category_name = _classify_file(project_file.path)
        file_symbols = symbols_by_file.get(project_file.id, [])
        node = ArchitectureNode(
            project_id=project.id, name=project_file.path, node_type="module",
            file_id=project_file.id,
            symbol_id=_representative_symbol(file_symbols),
            description=_describe_symbols(file_symbols),
            parent_node_id=categories[category_name].id,
        )
        nodes.append(node)
        file_nodes[project_file.id] = node
        for alias in _module_aliases(project_file.path):
            module_nodes.setdefault(alias, node)
        edges.append(_edge(project.id, categories[category_name], node, "contains"))

    if overview is not None:
        _add_overview_nodes(project.id, overview, categories, nodes, edges)

    seen: set[tuple[UUID, UUID]] = set()
    for code_import in imports:
        source = file_nodes.get(code_import.file_id)
        target = _resolve_import_node(code_import.module, module_nodes)
        if source is None or target is None or source.id == target.id:
            continue
        key = (source.id, target.id)
        if key not in seen:
            edges.append(_edge(project.id, source, target, "imports"))
            seen.add(key)

    edges.extend([
        _edge(project.id, categories["api"], categories["service"], "calls"),
        _edge(project.id, categories["service"], categories["database"], "accesses"),
    ])
    return ArchitectureMap(project_id=project.id, nodes=nodes, edges=edges)


def rebuild_project_architecture(
    project: Project,
    architecture_repository: ArchitectureRepository,
    file_repository: ProjectFileRepository,
    symbol_repository: CodeSymbolRepository,
    import_repository: CodeImportRepository,
    overview_repository: ProjectOverviewRepository,
) -> ArchitectureMap:
    """Read Modules 2-5, rebuild the graph, and atomically persist it."""
    architecture = build_architecture_map(
        project, file_repository.get_by_project_id(project.id),
        symbol_repository.get_by_project_id(project.id),
        import_repository.get_by_project_id(project.id),
        overview_repository.get_by_project_id(project.id),
    )
    return architecture_repository.save(architecture)


def _classify_file(path: str) -> ArchitectureNodeType:
    parts = {part.lower() for part in PurePosixPath(path).parts}
    stem = PurePosixPath(path).stem.lower()
    if parts & {"api", "apis", "router", "routers", "controller", "controllers"}:
        return "api"
    if parts & {"service", "services", "usecase", "usecases"}:
        return "service"
    if parts & {"database", "db", "repository", "repositories", "models"}:
        return "database"
    if stem in {"main", "app", "config", "settings"} or parts & {"core", "domain"}:
        return "core"
    return "core"


def _module_aliases(path: str) -> set[str]:
    normalized = str(PurePosixPath(path).with_suffix("")).replace("/", ".")
    aliases = {normalized}
    if normalized.endswith(".__init__"):
        aliases.add(normalized.removesuffix(".__init__"))
    parts = normalized.split(".")
    aliases.update(".".join(parts[index:]) for index in range(1, len(parts)))
    return aliases


def _resolve_import_node(module: str, nodes: dict[str, ArchitectureNode]) -> ArchitectureNode | None:
    module = module.lstrip(".")
    if module in nodes:
        return nodes[module]
    candidates = [(name, node) for name, node in nodes.items() if module.endswith(name) or name.endswith(module)]
    return max(candidates, key=lambda item: len(item[0]))[1] if candidates else None


def _representative_symbol(symbols: list[CodeSymbol]) -> UUID | None:
    top_level = [symbol for symbol in symbols if symbol.parent_symbol_id is None]
    return min(top_level, key=lambda item: item.start_line).id if top_level else None


def _describe_symbols(symbols: list[CodeSymbol]) -> str | None:
    names = [symbol.name for symbol in symbols if symbol.parent_symbol_id is None]
    return f"Symbols: {', '.join(names[:8])}" if names else None


def _add_overview_nodes(
    project_id: UUID, overview: ProjectOverview,
    categories: dict[ArchitectureNodeType, ArchitectureNode], nodes: list[ArchitectureNode],
    edges: list[ArchitectureEdge],
) -> None:
    details = {"api": overview.apis, "database": overview.databases, "core": overview.core_modules}
    existing = {(node.parent_node_id, node.name.casefold()) for node in nodes}
    for category_name, names in details.items():
        parent = categories[category_name]
        for name in names:
            key = (parent.id, name.casefold())
            if key in existing:
                continue
            node = ArchitectureNode(
                project_id=project_id, name=name, node_type="module",
                description="Derived from the project overview", parent_node_id=parent.id,
            )
            nodes.append(node)
            edges.append(_edge(project_id, parent, node, "contains"))
            existing.add(key)


def _edge(
    project_id: UUID,
    source: ArchitectureNode,
    target: ArchitectureNode,
    relation_type: ArchitectureRelationType,
) -> ArchitectureEdge:
    return ArchitectureEdge(
        project_id=project_id, source_node_id=source.id,
        target_node_id=target.id, relation_type=relation_type,
    )
